name: resume

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  PDF_FILE: 'AlexDumanskiy.pdf'

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: AlexDumanskiy/action-jsonresume-export@48aa5dfda7066a3a6fbbe94e31d28b227c48b95c
        name: Export resume as HTML
        with:
          theme: paper
          resume_filepath: resume.json
          output_format: html
          output_filepath: docs/index.html
      - uses: AlexDumanskiy/action-jsonresume-export@48aa5dfda7066a3a6fbbe94e31d28b227c48b95c
        name: Export resume as PDF
        with:
          theme: paper
          resume_filepath: resume.json
          output_format: pdf
          output_filepath: docs/${{ env.PDF_FILE }}
      - name: Commit published HTML
        id: commit-html
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain docs/index.html)" ]; then
            git add docs/index.html
            git commit -m "[ci skip] chore: update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Commit published PDF
        id: commit-pdf
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain docs/${{ env.PDF_FILE}} )" ]; then
            git add docs/${{ env.PDF_FILE }}
            git commit -m "[ci skip] chore: update resume pdf"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit-html.outputs.exit_code == 0 || steps.commit-pdf.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
