name: resume

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

inputs:
  pdf_file:
    description: 'Name of the PDF file to generate'
    required: false
    default: 'AlexDumanskiy.pdf'

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: AlexDumanskiy/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: paper
          resume_filepath: resume.json
          output_format: html
          output_filepath: docs/index.html
      - uses: AlexDumanskiy/action-jsonresume-export@v1
        name: Export resume as PDF
        with:
          theme: paper
          resume_filepath: resume.json
          output_format: pdf
          output_filepath: docs/${{ inputs.pdf_file }}
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain docs/index.html)" ]; then
            git add docs/index.html
            git add docs/${{ inputs.pdf_file }}
            git commit -m "[ci skip] chore: update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
